/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 cb44.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cb44.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.belt_top_ring.geometry} material={materials.initialShadingGroup} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.belt.geometry} material={materials['asdfasdf:initialShadingGroup_003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pinky_part.geometry} material={materials.blinn7SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.welting.geometry} material={materials['initialShadingGroup.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.binding.geometry} material={materials.blinn4SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.spagetti.geometry} material={materials['initialShadingGroup.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.middle_part.geometry} material={materials.blinn5SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ring_part.geometry} material={materials.blinn6SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.index_thumb_web.geometry} material={materials.huerta_Default_OBJ} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.laces_1.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.laces_2.geometry} material={materials['initialShadingGroup.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/cb44.glb')
