/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 untitled-v1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled-v1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[0.724, 0.889, -0.273]} rotation={[-0.005, 0.037, -0.076]} scale={0.949}>
          <mesh geometry={nodes.polySurface12583001.geometry} material={materials.Default_Material} />
          <mesh geometry={nodes.polySurface12586001.geometry} material={materials.Default_Material} />
          <mesh geometry={nodes.MASH4_ReproMesh1.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pDisc2.geometry} material={materials.lambert1} />
        </group>
        <mesh geometry={nodes.wrist_logo001.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.polySurface12583.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.polySurface12586.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.MASH4_ReproMesh.geometry} material={materials.lambert1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pDisc1.geometry} material={materials.lambert1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.wrist_logo002.geometry} material={materials.Default_Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.polySurface12587.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12588.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12589.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.wrist_logo.geometry} material={materials.Default_Material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[0.309, 0.241, -0.947]} scale={0.959}>
          <mesh geometry={nodes.body.geometry} material={materials['we1:web1']} />
          <mesh geometry={nodes.laces001.geometry} material={materials.Default_Material} />
          <mesh geometry={nodes.Mesh042.geometry} material={materials['we1:stiches1']} />
          <mesh geometry={nodes.Mesh042_1.geometry} material={materials['we1:web1']} />
        </group>
        <mesh geometry={nodes.polySurface11.geometry} material={materials['web2:web1']} />
        <mesh geometry={nodes.stitches001.geometry} material={materials['web2:stiches1']} />
        <mesh geometry={nodes.Mesh038.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Mesh038_1.geometry} material={materials['web2:laces1']} />
        <mesh geometry={nodes.laces002.geometry} material={materials['untitled:laces_002']} />
        <mesh geometry={nodes.stitches003.geometry} material={materials['untitled:stiches_002']} />
        <mesh geometry={nodes.Mesh045.geometry} material={materials['untitled:web_002']} />
        <mesh geometry={nodes.Mesh045_1.geometry} material={materials['untitled:stiches_002']} />
      </group>
      <mesh geometry={nodes.logo_fat_border.geometry} material={materials['initialShadingGroup.007']} position={[-0.004, 0.154, -0.034]} rotation={[1.604, -0.087, 2.659]} scale={0.414} />
      <mesh geometry={nodes.Logo1.geometry} material={materials.logo1} position={[0.108, 0.113, -0.01]} rotation={[1.857, -0.219, 2.422]} scale={0.011} />
      <mesh geometry={nodes.Logo2.geometry} material={materials.Logo2} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo3.geometry} material={materials.Logo3} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo4.geometry} material={materials.Logo4} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo5.geometry} material={materials.Logo5} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo6.geometry} material={materials.Logo6} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo7.geometry} material={materials.Logo7} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo8.geometry} material={materials.Logo8} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo9.geometry} material={materials.Logo9} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo10.geometry} material={materials.Logo10} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo11.geometry} material={materials.Logo11} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.MASH1_ReproMesh.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12580.geometry} material={materials.lambert1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.mesh_palm.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12590.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12591.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12593.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12595.geometry} material={materials.lambert1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.MASH2_ReproMesh.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12579.geometry} material={materials.lambert1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.MASH3_ReproMesh.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12582.geometry} material={materials['lambert1.001']} />
      </group>
      <mesh geometry={nodes.back.geometry} material={materials['web2:leather2']} />
      <mesh geometry={nodes.bindings.geometry} material={materials['web2:binding1']} />
      <mesh geometry={nodes.hole_cover.geometry} material={materials['web2:leather2']} />
      <mesh geometry={nodes.inlay.geometry} material={materials['web2:WebCrown1']} />
      <mesh geometry={nodes.single_stitch.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.wrist.geometry} material={materials['web2:wrist1']} />
      <mesh geometry={nodes.Mesh017.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Mesh017_1.geometry} material={materials.Default_Material} />
      <mesh geometry={nodes.polySurface12596.geometry} material={materials['web2:logo3']} />
      <mesh geometry={nodes.polySurface4478.geometry} material={materials['web2:logo3']} />
      <mesh geometry={nodes.polySurface4479.geometry} material={materials['web2:Logo_circle1']} />
      <mesh geometry={nodes.Mesh002.geometry} material={materials['web2:laces1']} />
      <mesh geometry={nodes.Mesh002_1.geometry} material={materials.Default_Material} />
      <mesh geometry={nodes.Mesh007.geometry} material={materials['web2:stiches1']} />
      <mesh geometry={nodes.Mesh007_1.geometry} material={materials['web2:web1']} />
    </group>
  )
}

useGLTF.preload('/untitled-v1.glb')
