/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 untitled.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Welt3001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Welt2001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Welt3.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Welt2.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Welt1.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.strips.geometry} material={materials.dwstrips} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.inside_palm_mesh.geometry} material={materials['Details 2']} position={[0.005, -0.025, -0.008]} rotation={[Math.PI / 2, 0, 0]} scale={[0.013, 0.013, 0.014]} />
      <mesh geometry={nodes.thumb_mesh_bot.geometry} material={materials['Details 2']} position={[-0.002, -0.001, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.thumb_mesh_top.geometry} material={materials['Details 2']} position={[-0.032, -0.058, 0.005]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.palm_mesh.geometry} material={materials['Details 2']} position={[0.017, 0.004, -0.009]} rotation={[1.688, 0.191, -0.136]} scale={0.01} />
      <mesh geometry={nodes.pinky_mesh.geometry} material={materials['Details 2']} position={[-0.005, 0.003, -0.028]} rotation={[1.532, -0.067, -0.765]} scale={0.01} />
      <mesh geometry={nodes.index_top_mesh.geometry} material={materials.Index_Inner1} position={[0.021, -0.003, 0.012]} rotation={[1.518, -0.013, 0.399]} scale={0.01} />
      <mesh geometry={nodes.Welt1001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.crown_patch001.geometry} material={materials.Crown_Patch} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.crown_lace.geometry} material={materials['Welting.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.logoback2.geometry} material={materials.Logo_Back} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.thuimb.geometry} material={materials.Thumb_Outer} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.inlay_l2.geometry} material={materials.inlay_l2} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.stitches1.geometry} material={materials.Stitches} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.side_logo1.geometry} material={materials.Side_Logo} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Wire.geometry} material={materials['Welting.001']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Pinky_Outer.geometry} material={materials.Pink_Outer} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Pinky_Inner1.geometry} material={materials.Pink_Inner} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Ring_Outer.geometry} material={materials.Ring_Outer} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Ring_Inner.geometry} material={materials.Ring_Inner} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Middle_Outer.geometry} material={materials['Middle Outer']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Thumb_Outer.geometry} material={materials.Thumb_Inner} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Index_Outer.geometry} material={materials.Index_Outer} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Index_Inner.geometry} material={materials.Index_Inner1} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Wire1.geometry} material={materials.Laces} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Dtail3.geometry} material={materials.Details} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Dtail2.geometry} material={materials.Details} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Lining.geometry} material={materials.Inside} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.Wrist.geometry} material={materials.Wrist} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.body_palm.geometry} material={materials.Palm} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.web10.geometry} material={materials.Basket} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web10_laces.geometry} material={materials.Web_Laces_9} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web10_stitches.geometry} material={materials.Web_Stitches_9} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web12_stitches.geometry} material={materials.Web_Stitches_10} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web12.geometry} material={materials.Web_Body_Y} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web12_laces.geometry} material={materials.Web_Laces_10} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web8_stitches.geometry} material={materials.Web_Stitches_6} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web8_laces.geometry} material={materials.Web_Laces_2} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web8.geometry} material={materials.Web_Body_4} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7.geometry} material={materials['Web 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7_laces.geometry} material={materials['Knots.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7_stitches.geometry} material={materials['Knots.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web6.geometry} material={materials['Knots.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web6_laces.geometry} material={materials.Web_Laces_3} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web6_stitches.geometry} material={materials.Web_Stitches_7} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.pCube1.geometry} material={materials['Details 2']} position={[0.046, 0.114, 0.036]} rotation={[1.359, -0.283, -0.829]} scale={[0.021, 0.001, 0.019]} />
      <mesh geometry={nodes.web11_laces001.geometry} material={materials.Web_Laces_8} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web11_stitches001.geometry} material={materials.Web_Stitches_8} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web4_laces_fr.geometry} material={materials.Web_Laces_4} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web4_stitches.geometry} material={materials['Web_Stitches 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web4.geometry} material={materials.Web_Body_2} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web3.geometry} material={materials.Net_Style} rotation={[Math.PI / 2, 0, -2.451]} scale={0.01} />
      <mesh geometry={nodes.web3_laces.geometry} material={materials.Web_Laces_5} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web3_stitches.geometry} material={materials.Web_Stitches_4} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web2_laces.geometry} material={materials.Web_Laces_6} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web2_stitches.geometry} material={materials.Web_Stitches_3} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web2_body.geometry} material={materials.Web_Body} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web1_laces.geometry} material={materials.Web_Stitches} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web1_stitches.geometry} material={materials['Web_Stitches.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web1_body.geometry} material={materials.Web} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9.geometry} material={materials.Web_Body_5a} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9_laces.geometry} material={materials['Knots.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9_stitches.geometry} material={materials.Web_Stitches_5} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web11_laces.geometry} material={materials.Web_Laces_8} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.logoback.geometry} material={materials['Logo Back 2']} position={[-0.007, 0, -0.006]} rotation={[Math.PI / 2, 0, -2.451]} scale={0.01} />
      <mesh geometry={nodes.weblogo.geometry} material={materials.Web_Logo} position={[-0.007, 0, -0.006]} rotation={[Math.PI / 2, 0, -2.451]} scale={0.01} />
      <mesh geometry={nodes.web11_stitches.geometry} material={materials.Web_Stitches_8} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web11.geometry} material={materials.Web_Base} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web5.geometry} material={materials.Web_Body_3} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web_5_laces.geometry} material={materials.Web_Laces_7} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web_5_stitches.geometry} material={materials.web5stitches} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.logo_outline314.geometry} material={materials['Logo Outline']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.legend_logo1.geometry} material={materials['Logo Without Outline 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.logo_without_outline001.geometry} material={materials['Logo Without Outline']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inside_line_square_logo.geometry} material={materials['Logo Inner Line']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.outside_line_square_logo.geometry} material={materials['Logo Outside Line']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.square_logo_patch.geometry} material={materials['Square Logo Patch']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.square_logo_3.geometry} material={materials.Square_Logo_Letters} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.MASH1_ReproMesh.geometry} material={materials['Details 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.index_finger_hood.geometry} material={materials['hood.001']} position={[0, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.MASH1_ReproMesh1.geometry} material={materials['Details 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.index_finger_pad.geometry} material={materials['hood.001']} position={[0, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.MASH2_ReproMesh1.geometry} material={materials['Details 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.middle_finger_pad.geometry} material={materials['hood.001']} position={[0, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.MASH2_ReproMesh.geometry} material={materials['Details 2']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.logo_stitch_round.geometry} material={materials['Logo Stitches']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.circle_logo001.geometry} material={materials.Circle_Logo} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.legend_logo.geometry} material={materials.Circle_Logo_Lettersa} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Middle_Inner.geometry} material={materials.Middle_Inner} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.square_logo_outline.geometry} material={materials['Logo Outline.001']} position={[-0.002, 0.005, 0.013]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
      <mesh geometry={nodes.Wire001.geometry} material={materials.welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.flag_logo.geometry} material={materials.logo_with_outline1} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.dual_welt002.geometry} material={materials['lambert1.001']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dual_welt001.geometry} material={materials['Details 2.001']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.web6001.geometry} material={materials['Knots.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web6_laces001.geometry} material={materials['Web_Laces_3.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web6_stitches001.geometry} material={materials['Web_Stitches_7.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9001.geometry} material={materials['Web_Body_5a.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9_laces001.geometry} material={materials['Knots.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web9_stitches001.geometry} material={materials['Web_Stitches_5.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7001.geometry} material={materials['Web 2.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7_laces001.geometry} material={materials['Knots.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.web7_stitches001.geometry} material={materials['Knots.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.dualwelt_index.geometry} material={materials['Details 2.002']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dualwelt_middle.geometry} material={materials['Details 2.003']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dual_welt1.geometry} material={materials['Welting.002']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dual_welt2.geometry} material={materials.welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dual_welt3.geometry} material={materials['Welting.002']} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.dual_welt4.geometry} material={materials.welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.inlay_l3.geometry} material={materials.inlay_l3} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inlay_l4.geometry} material={materials.inlay_l4} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inlay_l6.geometry} material={materials.inlay_l6} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inlay_l8.geometry} material={materials.inlay_l8} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inlay_l5.geometry} material={materials.inlay_l5} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.inlay_l7.geometry} material={materials.inlay_l7} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.middle_finger_pad1.geometry} material={materials['Details 2.004']} position={[0, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.shaka.geometry} material={materials.shaka} position={[0.036, 0.039, 0.023]} rotation={[2.744, 0.257, -1.083]} scale={0.01} />
      <mesh geometry={nodes.shaka_premium.geometry} material={materials.ilovetacos} position={[0.036, 0.039, 0.023]} rotation={[2.744, 0.257, -1.083]} scale={0.01} />
      <mesh geometry={nodes.shaka_text.geometry} material={materials['default']} position={[0.037, 0.033, 0.014]} rotation={[2.744, 0.257, -1.083]} scale={0.02} />
      <mesh geometry={nodes.logo_text.geometry} material={materials['initialShadingGroup.005']} position={[-0.025, 0, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.414} />
      <mesh geometry={nodes.logo_stitch.geometry} material={materials['initialShadingGroup.006']} position={[-0.025, 0, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.414} />
      <mesh geometry={nodes.logo_patch.geometry} material={materials.d_initialShadingGroup} position={[-0.025, 0, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.414} />
      <mesh geometry={nodes.logo_fat_border.geometry} material={materials['initialShadingGroup.007']} position={[-0.025, 0, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.414} />
      <mesh geometry={nodes.T_web_laces.geometry} material={materials.blinn1SG} position={[-0.005, 0.007, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Y_web_laces.geometry} material={materials['blinn1SG.001']} position={[0.042, 0.115, 0.034]} rotation={[1.635, -0.03, 0.03]} />
      <group position={[-0.024, -0.002, 0.028]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
        <mesh geometry={nodes['2'].geometry} material={materials['blinn1SG.002']} />
        <mesh geometry={nodes['2_1'].geometry} material={materials['huerta_initialShadingGroup_003.001']} />
        <mesh geometry={nodes['2_2'].geometry} material={materials['blinn2SG.001']} />
      </group>
      <mesh geometry={nodes.dual_welting_thumb_part.geometry} material={materials.newthumb} position={[-0.021, 0.002, 0.029]} rotation={[Math.PI / 2, 0, 0]} scale={0.387} />
      <mesh geometry={nodes.web_H_new.geometry} material={materials['initialShadingGroup.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.web_H_new_stitches.geometry} material={materials['s:web6stitches']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.web4_laces_fr001.geometry} material={materials.web4_laces} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.newTest.geometry} material={materials.initialShadingGroup} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Logo1.geometry} material={materials.logo1} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo2.geometry} material={materials.Logo2} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo3.geometry} material={materials.Logo3} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo4.geometry} material={materials.Logo4} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo5.geometry} material={materials.Logo5} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo6.geometry} material={materials.Logo6} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo7.geometry} material={materials.Logo7} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo8.geometry} material={materials.Logo8} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo9.geometry} material={materials.Logo9} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo10.geometry} material={materials.Logo10} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Logo11.geometry} material={materials.Logo11} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.laces.geometry} material={materials['initialShadingGroup.011']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.stitches.geometry} material={materials['initialShadingGroup.012']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body.geometry} material={materials['initialShadingGroup.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.web_2.geometry} material={materials['initialShadingGroup.013']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.web_2_stitches.geometry} material={materials['initialShadingGroup.014']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.web_2_laces.geometry} material={materials['initialShadingGroup.015']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.polySurface297.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface297001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface298.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface299.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface299001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface300.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface300001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface301.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface301001.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface302.geometry} material={materials.Knots} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface302001.geometry} material={materials.Knots} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface307.geometry} material={materials.Palm} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface311.geometry} material={materials.Welting} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface312.geometry} material={materials.Welting} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface313.geometry} material={materials.Welting} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface319.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface320.geometry} material={materials.Welting} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface321.geometry} material={materials.Knots} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface328.geometry} material={materials.inlay_l1} position={[-0.071, 0.03, 0.01]} rotation={[-2.025, 0.713, 1.43]} scale={-0.01} />
      <mesh geometry={nodes.polySurface332.geometry} material={materials.Thumb_Outer} position={[-0.007, 0.013, 0.009]} rotation={[1.617, -0.085, -2.45]} scale={0.008} />
      <mesh geometry={nodes.polySurface333.geometry} material={materials.Side_Logo} position={[-0.039, -0.004, 0.008]} rotation={[1.659, -0.185, -2.459]} scale={0.012} />
      <mesh geometry={nodes.polySurface334.geometry} material={materials.Side_Logo} position={[-0.039, -0.004, 0.008]} rotation={[1.659, -0.185, -2.459]} scale={0.012} />
      <mesh geometry={nodes.polySurface335.geometry} material={materials.Web_Base} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface337.geometry} material={materials.Web_Base} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[-0.061, 0.085, -0.011]} rotation={[1.204, -0.015, 0.413]} scale={0.027}>
        <mesh geometry={nodes['1_stitch_1'].geometry} material={materials['blinn3SG.001']} />
        <mesh geometry={nodes['1_stitch_2'].geometry} material={materials.blinn3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
