/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 CatcherWristFixed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CatcherWristFixed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.pasted__polySurface1.geometry} material={materials.hood} />
        <mesh geometry={nodes.pasted__polySurface2.geometry} material={materials.pad} />
        <mesh geometry={nodes.Mesh002.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials.pasted__logo_without_outline_fr} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-0.219, 0.172, 0.621]}>
          <mesh geometry={nodes.logo001.geometry} material={materials.pasted__logo_without_outline_fr} />
          <mesh geometry={nodes.MASH16_ReproMesh.geometry} material={materials.blinn17} />
          <mesh geometry={nodes.pCylinder29.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface110.geometry} material={materials.blinn16} />
        </group>
        <group position={[41.558, 7.027, -16.35]} rotation={[-2.442, 1.336, 3.113]} scale={1.4}>
          <mesh geometry={nodes.logo_backup1001.geometry} material={materials.pasted__logo_without_outline_fr} />
          <mesh geometry={nodes.polySurface111001.geometry} material={materials.blinn13} />
          <mesh geometry={nodes.polySurface112001.geometry} material={materials.blinn11} />
          <mesh geometry={nodes.polySurface113001.geometry} material={materials.blinn12} />
          <mesh geometry={nodes.polySurface114001.geometry} material={materials.blinn12} />
          <mesh geometry={nodes.polySurface115001.geometry} material={materials.blinn11} />
        </group>
        <mesh geometry={nodes.logo_backup.geometry} material={materials.pasted__logo_without_outline_fr} position={[0.851, 2.603, 2.981]} rotation={[-0.058, 0.045, -0.048]} scale={1.235} />
        <mesh geometry={nodes.polySurface117001.geometry} material={materials.blinn15} position={[-0.219, 0.172, 0.621]} />
        <mesh geometry={nodes.polySurface120001.geometry} material={materials.pasted__logo_without_outline_fr} position={[-0.219, 0.172, 0.621]} />
        <mesh geometry={nodes.logo_backup1.geometry} material={materials.pasted__logo_without_outline_fr} position={[0.267, 1.197, -1.272]} rotation={[-0.058, 0.045, -0.048]} scale={0.921} />
        <mesh geometry={nodes.polySurface111.geometry} material={materials.blinn13} position={[-0.748, -3.671, -15.388]} rotation={[-2.256, 0.252, -0.051]} scale={[3.666, 2.288, 2.055]} />
        <mesh geometry={nodes.polySurface112.geometry} material={materials.blinn11} position={[-0.748, -3.671, -15.388]} rotation={[-2.256, 0.252, -0.051]} scale={[3.666, 2.288, 2.055]} />
        <mesh geometry={nodes.polySurface113.geometry} material={materials.blinn12} position={[-0.748, -3.671, -15.388]} rotation={[-2.256, 0.252, -0.051]} scale={[3.666, 2.288, 2.055]} />
        <mesh geometry={nodes.polySurface114.geometry} material={materials.blinn12} position={[-0.748, -3.671, -15.388]} rotation={[-2.256, 0.252, -0.051]} scale={[3.666, 2.288, 2.055]} />
        <mesh geometry={nodes.polySurface115.geometry} material={materials.blinn11} position={[-0.748, -3.671, -15.388]} rotation={[-2.256, 0.252, -0.051]} scale={[3.666, 2.288, 2.055]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.sweep1.geometry} material={materials.binding} />
        <mesh geometry={nodes.sweep3.geometry} material={materials.binding} />
        <mesh geometry={nodes.sweep6.geometry} material={materials.binding} />
        <mesh geometry={nodes.sweep7.geometry} material={materials.binding} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.polySurface19.geometry} material={materials.palm_1} />
        <mesh geometry={nodes.polySurface6.geometry} material={materials.leather1} />
        <mesh geometry={nodes.polySurface7.geometry} material={materials.leather1_1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.polySurface9.geometry} material={materials['leather1_2.001']} />
        <mesh geometry={nodes.polySurface9004.geometry} material={materials.Wrist} position={[-36.984, -0.046, 0]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh033.geometry} material={materials.laces1} />
        <mesh geometry={nodes.Mesh033_1.geometry} material={materials.laces2} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh034.geometry} material={materials.Stitches2} />
        <mesh geometry={nodes.Mesh034_1.geometry} material={materials.Stitches1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh036.geometry} material={materials.Palm} />
        <mesh geometry={nodes.Mesh036_1.geometry} material={materials.pasted__logo_without_outline_fr} />
      </group>
      <mesh geometry={nodes.logo_fat_border.geometry} material={materials['initialShadingGroup.007']} position={[-0.004, 0.154, -0.034]} rotation={[1.604, -0.087, 2.659]} scale={0.414} />
      <mesh geometry={nodes.logo_patch.geometry} material={materials.d_initialShadingGroup} position={[-0.004, 0.153, -0.032]} rotation={[1.604, -0.087, 2.659]} scale={0.414} />
      <mesh geometry={nodes.logo_stitch.geometry} material={materials['initialShadingGroup.006']} position={[-0.004, 0.155, -0.033]} rotation={[1.604, -0.087, 2.659]} scale={0.414} />
      <mesh geometry={nodes.logo_text.geometry} material={materials['initialShadingGroup.005']} position={[-0.003, 0.153, -0.034]} rotation={[1.604, -0.087, 2.659]} scale={0.414} />
      <mesh geometry={nodes.Logo1.geometry} material={materials.logo1} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo2.geometry} material={materials.Logo2} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo3.geometry} material={materials.Logo3} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo4.geometry} material={materials.Logo4} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo5.geometry} material={materials.Logo5} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo6.geometry} material={materials.Logo6} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo7.geometry} material={materials.Logo7} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo8.geometry} material={materials.Logo8} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo9.geometry} material={materials.Logo9} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo10.geometry} material={materials.Logo10} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.Logo11.geometry} material={materials.Logo11} position={[-0.004, 0.153, -0.029]} rotation={[1.7, -0.105, 2.552]} scale={0.011} />
      <mesh geometry={nodes.cross.geometry} material={materials.cross} position={[-0.07, 0.207, 0.022]} rotation={[0.131, -0.422, -1.208]} scale={0.05} />
      <mesh geometry={nodes.polySurface10.geometry} material={materials.crown} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface14.geometry} material={materials.web} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/CatcherWristFixed.glb')
